"""Remove message, added pill

Revision ID: 3d0617a86870
Revises: 7a67ff8c445b
Create Date: 2024-12-16 13:12:50.663300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0617a86870'
down_revision = '7a67ff8c445b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pills', sa.Integer(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('pills')

    # ### end Alembic commands ###
