"""Add schedule model

Revision ID: caee6d49395f
Revises:
Create Date: 2024-12-05 10:26:42.402037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee6d49395f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Enum('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', name='dayofweek'), nullable=False),
    sa.Column('remind_time', sa.Time(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
